channels:
  - conda-forge
dependencies:
  - cartopy
  - fsspec
  - pyviz/label/dev::hvplot
  - pyviz/label/dev::holoviews
  - pyviz/label/dev::panel
  - pyviz/label/dev::datashader
  - xarray
  - zarr
  - netcdf4
  - intake
  - intake-xarray
  - metpy
  - requests
  - pip
  - pip:
    - git+https://github.com/pyviz/geoviews.git
