channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - xarray
  - zarr
  - netcdf4
  - bokeh  
  - datashader
  - holoviews  
  - geoviews
  - hvplot  
  - panel
  - intake
  - intake-xarray
  - metpy
